//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Players
    {
        public T_Players()
        {
            this.T_Bid = new HashSet<T_Bid>();
        }
    
        public int PlayerId { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Type { get; set; }
        public Nullable<int> Matches { get; set; }
        public Nullable<int> Runs { get; set; }
        public Nullable<int> Wickets { get; set; }
        public bool Status { get; set; }
        public double BasePrice { get; set; }
    
        public virtual ICollection<T_Bid> T_Bid { get; set; }
    }
}
